quartz:
  enable: true

server:
  port: 9090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/chinaQuartz
    username: root
    password: 1234
    # tomcat:
    #   initialSize: 20
    #   maxActive: 100
    #   maxIdle: 100
    #   minIdle: 20
    #   maxWait: 10000
    #   testWhileIdle: true
    #   testOnBorrow: false
    #   testOnReturn: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  batch:
    initialize-schema: always # 배치 스키마를 항상 초기화하도록 설정합니다. (개발 환경에서만 사용해야 합니다.)
    datasource:
      url: jdbc:mysql://localhost:3306/chinaQuartz # 배치 작업용 데이터베이스 URL
      username: root # 배치 작업용 데이터베이스 접속 사용자명
      password: 1234 # 배치 작업용 데이터베이스 접속 비밀번호

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
    job-store:
      use-properties: false

# 로그 프로필 가져오기
##=====================================  log  =============================
# logging:
#   config: classpath:log4j2.xml
